### ISSUE TITLE
CI/CD introduction

### ISSUE THREAD

**Issue by vivi90** [HTWK-18INB-1/harae#3]
Continuous integration and deployment would be great to check at least compile errors and publish every current version in an easy way.

**Comment by vivi90** [comment]
### Possible solution
[GameCI](https://game.ci/docs)

**Comment by vivi90** [comment]
Build seems to work but tests not (see: https://github.com/game-ci/unity-test-runner/issues/95)

**Comment by vivi90** [comment]
Okay, applied:

- https://github.com/game-ci/unity-actions/issues/84
- https://github.com/game-ci/unity-test-runner/issues/58

But still not works:

`2021-02-19T13:18:05.9100714Z failed to register layer: Error processing tar file(exit status 1): write /opt/unity/Editor/Data/Resources/PackageManager/ProjectTemplates/libcache/com.unity.template.universal-8.3.1/Artifacts/29/29f052f219c4b50957a4ff15cced88d2: no space left on device`

**Comment by vivi90** [comment]
CI workflow now works.
CD workflow still in progress.

**Comment by vivi90** [comment]
Current not used unfinished CD draft:
```yaml
# GitHub Actions release workflow
#
# Created: 2021 by Vivien Richter <vivien-richter@outlook.de>
#
# License: CC BY 4.0
name: Release

# Controls when the action will run.
on:
  # Triggers the workflow on workflow_run events but only for the same branch and if completed.
  workflow_run:
    workflows:
      - Build
    types:
      - completed

  # Triggers the workflow on push tag events
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets environment variables
env:
  REQUEST_RETRY_NUMBER: 3
  REQUEST_RETRY_DELAY: 5 # in seconds
  API_URL_GITHUB: ${{github.api_url}}
  # This token is provided by Actions, you do not need to create your own token
  GITHUB_TOKEN: ${{github.token}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: Release 🎉
    runs-on: ubuntu-latest
    steps:

      - name: Tag read
        run: echo "${{ toJson(github) }}"

      # Checks last CI result
      - name: Check last CI result
        run: >
          RUN_CONCLUSION=$(curl -s --retry "$REQUEST_RETRY_NUMBER" --retry-delay "$REQUEST_RETRY_DELAY"
          -H "Accept: application/vnd.github.v3+json"
          -X GET "$API_URL_GITHUB/repos/vivi90/test/actions/workflows/unity_ci.yml/runs"
          -d "{\"content_type\": \"Issue\", \"content_id\": ${{env.ISSUE_ID}}}"
          | jq -r '.workflow_runs[0].conclusion')

          echo "Last CI run conclusion: $RUN_CONCLUSION"

          if [ "$RUN_CONCLUSION" != "success" ]; then
            exit 1;
          fi

      # Loads build workflow artifacts
      - name: Load build artifacts
        uses: dawidd6/action-download-artifact@v2.11.1
        with:
          workflow: unity_ci.yml
          workflow_conclusion: success
          name: Builds
          path: Builds

      # Shows loaded files
      - name: Display structure of downloaded files
        run: |
          ls -R Builds

      # Creates release
```
